In [2]:
import numpy as np

In [3]:
d1=np.array([10,20,30,40,50])
d1

array([10, 20, 30, 40, 50])

In [4]:
d1.shape

(5,)

In [5]:
d1.size

5

In [6]:
d1[1:3]

array([20, 30])

In [7]:
data=np.array(["ranga",123,"cse",'A',2.5])

In [8]:
data

array(['ranga', '123', 'cse', 'A', '2.5'], dtype='<U5')

In [9]:
import time

start_time = time.time()
list1 = [x for x in range(1,100000)]
list2 = [y for y in range(1,100000)]

op = list(map(lambda x,y : x*y,list1,list2))
end_time = time.time()

print(" time taken by list concept",end_time-start_time)

 time taken by list concept 0.0312502384185791


In [11]:
import time
start_time1=time.time()
ar1=np.array(list1)
ar2=np.array(list2)
ar1*ar2
end_time1=time.time()
print(end_time1-start_time1)

0.0


In [13]:
d2=np.array([[10,20,30],[40,50,60],[70,80,90]])
d2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
d2[0]

array([10, 20, 30])

In [15]:
d2[0][0]

10

In [16]:
d2[0].max()

30

In [17]:
d2[:,1]

array([20, 50, 80])

In [19]:
d2[:,1].min()

20

In [20]:
d2[:,0].sum()

120

In [23]:
 for i in range(1,10):
        print(i,end=" ")
                

1 2 3 4 5 6 7 8 9 

In [25]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [27]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [31]:
name="MOUNIKA"
name

'MOUNIKA'

In [32]:
mat=np.arange(1,10,0.5)

In [33]:
mat

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [34]:
mat1=np.linspace(1,10,20)

In [35]:
m=mat+mat1

ValueError: operands could not be broadcast together with shapes (18,) (20,) 

In [36]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b

In [37]:
c

array([5, 7, 9])

In [38]:
np.random.random(10)

array([0.21259139, 0.03452108, 0.5241447 , 0.71747561, 0.08419319,
       0.24776244, 0.4902196 , 0.54643515, 0.96141351, 0.0302921 ])

In [40]:
np.random.random(1,100)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [41]:
np.random.randint(10,20,5)

array([13, 16, 13, 10, 15])

In [42]:
np.random.randint(1,25,[4,6])

array([[11, 18,  5, 10, 23, 18],
       [11, 12,  8,  1,  6, 10],
       [ 3, 11,  2, 10,  9,  9],
       [17, 10, 12, 15, 19, 12]])

In [43]:
np.random.rand(10)

array([0.93003081, 0.27299989, 0.32289663, 0.88897468, 0.90405578,
       0.15875729, 0.3622109 , 0.99062008, 0.67601268, 0.48912613])

In [44]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])